version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # gRPC port
      - "6334:6334"  # REST API port
    volumes:
      - ./qdrant_storage:/qdrant/storage  # Persist data locally
    # Optional: Configure API key if needed
    # environment:
    #   QDRANT__SERVICE__API_KEY: your_secret_api_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  qdrant_storage: 